[package]
name = "serde_flexitos"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = "1"
erased-serde = "0.3"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
linkme = "0.3"
once_cell = "1"
paste = "1"

[features]
default = ["id_trait"]
id_trait = []
