[package]
name = "serde_flexitos"
version = "0.1.0"
description = "Flexible serialization and deserialization of trait objects with serde"
repository = "https://github.com/Gohla/serde_flexitos"
edition = "2021"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
license = "Apache-2.0"

[dependencies]
serde = "1"
erased-serde = "0.3"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
linkme = "0.3"
once_cell = "1"
paste = "1"

[features]
default = ["id_trait"]
id_trait = []
