tag-name = "release/{{version}}"
tag-message = "Release {{version}}"
pre-release-commit-message = "Release {{version}}"
pre-release-replacements = [
  { file = "CHANGELOG.md", search = "## \\[Unreleased\\]", replace = "## [Unreleased]\n\n\n## [{{version}}] - {{date}}", exactly = 1 },
  { file = "CHANGELOG.md", search = "^\\[Unreleased\\]: ?(?<base>.+?/compare)/(?<prev>.+?)(?:\\.\\.\\.HEAD)", replace = "[Unreleased]: $base/{{tag_name}}...HEAD\n[{{version}}]: $base/$prev...{{tag_name}}", exactly = 1 },
]
